//popular players for random
var newPlayers = [
    "Zion Williamson",
    "Luka Doncic",
    "Lamelo Ball",
    "James Harden",
    "Kyrie Irving",
    "Julius Randle",
    "Devin Booker",
    "Ja Morant",
    "Damian Lillard",
    "Ben Simmons",
    "Joel Embiid",
    "Nikola Jokic",
    "Jamal Murray",
    "Jaylen Brown",
    "Jayson Tatum",
    "Bam Adebayo",
    "Zach Lavine",
    "Giannis Antetokounmpo",
    "Donovan Mitchell",
    "Anthony Davis",
    "Bradley Beal",
    "Trae Young",
    "Brandon Ingram",
    "De'Aaron Fox",
    "Collin Sexton",
    "Pascal Siakam",
    "Karl-Anthony Towns",
    "Domantas Sabonis",
    "Lonzo Ball",
    "Anthony Edwards",
    "John Collins",
    "Tyrese Haliburton",
    "Tyler Herro",
    "Kristaps Porzingis",
    "Jaren Jackson Jr.",
    "Deandre Ayton",
    "Jerami Grant",
    "James Wiseman",
    "Cade Cunningham",
    "Jalen Green",
    "Evan Mobley",
    "Scottie Barnes"
    ]
    
    var oldPlayers = ["Larry Bird",
    "Magic Johnson",
    "Julius Erving",
    "Kareem Abdul-Jabbar",
    "Wilt Chamberlain",
    "Moses Malone",
    "Patrick Ewing",
    "Shawn Kemp",
    "Charles Barkley",
    "Shaquille O'Neal",
    "Phil Jackson",
    "Reggie Miller",
    "Karl Malone",
    "Dominique Wilkins",
    "Clyde Drexler",
    "John Stockton",
    "George Gervin",
    "James Worthy",
    "Isiah Thomas",
    "John Havlicek",
    "Rick Barry",
    "Bill Russell",
    "George Mikan",
    "Pete Maravich",
    "Walt Frazier",
    "Jerry West",
    "Bill Walton",
    "Hakeem Olajuwon",
    "David Robinson",
    "Michael Jordan",
    "Chris Mullin",
    "Scottie Pippen",
    "Elgin Baylor",
    "Oscar Robertson",
    "Elvin Hayes",
    "Alex English",
    "Willis Reed",
    "Bob Cousy"    
    ]
    
    
    function randomOld(){
        var player = oldPlayers[Math.floor(Math.random()*oldPlayers.length)]
        document.querySelector("#playerInput2").value = player
    }
    
    function randomNew(){
        var player = newPlayers[Math.floor(Math.random()*newPlayers.length)]
        document.querySelector("#playerInput1").value = player
    }