var newPlayers = [
    "Zion Williamson",
    "Luka Doncic",
    "Lamelo Ball",
    "James Harden",
    "Kyrie Irving",
    "Julius Randle",
    "Devin Booker",
    "Ja Morant",
    "Damian Lillard",
    "Ben Simmons",
    "Joel Embiid",
    "Nikola Jokic",
    "Jamal Murray",
    "Jaylen Brown",
    "Jayson Tatum",
    "Bam Adebayo",
    "Zach Lavine",
    "Giannis Antetokounmpo",
    "Donovan Mitchell",
    "Anthony Davis",
    "Bradley Beal",
    "Trae Young",
    "Brandon Ingram",
    "De'Aaron Fox",
    "Collin Sexton",
    "Pascal Siakam",
    "Karl-Anthony Towns",
    "Domantas Sabonis",
    "Lonzo Ball",
    "Anthony Edwards"
];

var oldPlayers = [
    "Larry Bird",
    "Magic Johnson",
    "Julius Erving",
    "Kareem Abdul-Jabbar",
    "Wilt Chamberlain",
    "Moses Malone",
    "Patrick Ewing",
    "Shawn Kemp",
    "Charles Barkley",
    "Shaquille O'Neal",
    "Phil Jackson",
    "Reggie Miller",
    "Karl Malone",
    "Dominique Wilkins",
    "Clyde Drexler",
    "John Stockton",
    "George Gervin",
    "James Worthy",
    "Isiah Thomas",
    "John Havlicek",
    "Rick Barry",
    "Bill Russell"
]